### ISSUE TITLE
Asset not found on `npm start`

### ISSUE THREAD

**Issue by mcshakes** [expo/audio-recording-example#20]
**the Error**

```
Error: Asset not found: /Users/macmccarthy/Documents/learning/audio-recording-example/assets/icon.png for platform: null
    at /Users/macmccarthy/Documents/learning/audio-recording-example/node_modules/metro/src/Assets.js:188:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/macmccarthy/Documents/learning/audio-recording-example/node_modules/metro/src/Assets.js:52:24)
    at _next (/Users/macmccarthy/Documents/learning/audio-recording-example/node_modules/metro/src/Assets.js:72:9)
```

**Steps I Take:**

- Download/clone
- expo install
- npm start

**Comment by LawrenceNorman** [comment]
I saw this as well.

**Comment by IjzerenHein** [comment]
Hi! I was unable to reproduce this using expo-cli `3.22.0` and `3.24.0`.
We've also just updated the example to sdk 38. Could you try using the latest expo-cli and the latest code from master?
